version: '3.9'
services:
  katify-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.katify-frontend.rule=Host(`katify.ru`) || Host(`www.katify.ru`)
      - traefik.http.routers.katify-frontend.entrypoints=websecure
      - traefik.http.routers.katify-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.katify-frontend.loadbalancer.server.port=80
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
