version: '3.9'
services:
  katify-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.katify-frontend-dev.rule=Host(`dev.katify.ru`) && !PathPrefix(`/api`)
      - traefik.http.routers.katify-frontend-dev.entrypoints=websecure
      - traefik.http.routers.katify-frontend-dev.tls.certresolver=letsencrypt
      - traefik.http.services.katify-frontend-dev.loadbalancer.server.port=80

      - traefik.http.routers.katify-frontend-dev-www.rule=Host(`www.dev.katify.ru`)
      - traefik.http.routers.katify-frontend-dev-www.entrypoints=websecure
      - traefik.http.routers.katify-frontend-dev-www.middlewares=redirect-www-to-root@file
      - traefik.http.routers.katify-frontend-dev-www.service=katify-frontend-dev
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
